### ISSUE TITLE
~RESET line is not configured on new CPUs

### ISSUE THREAD

**Issue by netik** [netik/dc27_badge#4]
Bill will figure out how to configure this register (PSELRESET0/PSELRESET1)

**Comment by netik** [comment]
Bill figured this out, but now it needs to go into a script for programming in production.

Bill, what's the magic command?

**Comment by Bill-Paul** [comment]
There is no magic command. There is only Zuul.
No, seriously: there is now some code in the main() function of the firmware that will check if the UICR->PSELRESET[] fields are set correctly, and if it'll reflash the UICR on the fly to fix it.

The only catch is that you have to reboot the target once after the update for the change to take effect (the CPU only samples UICR->PSELRESET[] at start-up). So basically the procedure is:

1) Flash the firmware
2) Boot up the badge
3) Watch for the message below:

SYSTEM START
Reset event (0x4): Soft reset
Nordic Semiconductor nRF52840 Variant: AAAA RAM: 256KB Flash: 1024KB
Device ID: DA788BE24D13B5BB
Compact kernel mode
Reset pin not configured, programming... Done.                 <----------
Priority levels 8
[...]

4) Optional: power cycle the board and check that the reset button now works.

**Comment by Bill-Paul** [comment]
Fixed by commit 5664404ae0a65e35376aef35dee8ed855b5eee38
